server:
  port: 8083
  address: 127.0.0.1
spring:
  application:
    name: user-service
  # === THIS SECTION IS MISSING AND MUST BE ADDED ===
  security:
    oauth2:
      resourceserver:
        jwt:
          # This line tells Spring Security where to find your Keycloak realm to validate tokens
          issuer-uri: http://localhost:8180/realms/ISI-Platform
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
# This is your existing configuration for the admin client
keycloak:
  admin-client:
    server-url: http://localhost:8180
    # NOUVEAU: Le realm pour l'authentification de l'admin
    admin-realm: master
    # NOUVEAU: Le client ID pour l'admin
    admin-client-id: admin-cli
    # NOUVEAU: Le nom d'utilisateur de l'admin (avec une valeur par défaut pour le dev)
    admin-username: ${KEYCLOAK_ADMIN_USER:admin}
    # NOUVEAU: Le mot de passe de l'admin (avec une valeur par défaut pour le dev)
    admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    # Le realm que notre service doit gérer
    target-realm: ISI-Platform
